### ISSUE TITLE
Failed to compile latest release

### ISSUE THREAD

**Issue by johnlepikhin** [mamrhein/quantities.rs#15]
Latest release fails to compile due to broken dependency:

```
error: failed to select a version for the requirement `fpdec = "^0.7"`
candidate versions found which didn't match: 0.10.3, 0.9.0, 0.8.1
location searched: crates.io index
required by package `quantities v0.12.0`
    ... which satisfies dependency `quantities = "^0.12.0"`
```
Version 0.7 of fpdev has been unpublished, but fix is already there: https://github.com/mamrhein/quantities.rs/commit/01aa0048c4a80c162975b142b6ff6ebeb3ec772d . So, all we need is to publish a new release with that fix.

**Comment by mamrhein** [comment]
Resolved in version 0.12.1.

Thx for the hint!
