### ISSUE TITLE
PR for additional units.

### ISSUE THREAD

**Issue by luke-magnusson** [mamrhein/quantities.rs#3]
Dear Mr Amrhein.

I your project is great and was wondering if I could contribute some additional units for distance, time, and mass, for better functionality with astronomical workloads.

I have a working implementation ready, am open to change or drop it (in part or in full) if it's out of the scope of this repository, and I am still pretty new to contributing to open source software, so I would appreciate any notes or critiques you have.

## Units added in the fork:

- Duration
  - [Sidereal Day](https://en.wikipedia.org/wiki/Sidereal_time)
  - [Julian Year](https://en.wikipedia.org/wiki/Julian_year_(astronomy))
  - [Gregorian Year](https://en.wikipedia.org/wiki/Gregorian_year)
  - [Earth Period](https://en.wikipedia.org/wiki/Orbital_period#Examples_of_sidereal_and_synodic_periods)
- Length
  - [Light Second](https://en.wikipedia.org/wiki/Light-second)
  - [Light Year](https://en.wikipedia.org/wiki/Light-year)
  - [Astronomical Unit](https://en.wikipedia.org/wiki/Astronomical_unit)
  - [Parsec](https://en.wikipedia.org/wiki/Parsec)
- Mass
  - [Solar Mass](https://en.wikipedia.org/wiki/Solar_mass)
  - [Earth Mass](https://en.wikipedia.org/wiki/Earth_mass)
  - Lunar Mass
  - [Jupiter Mass](https://en.wikipedia.org/wiki/Jupiter_mass)
- Speed
   - [Speed of Light](https://en.wikipedia.org/wiki/Speed_of_light)

— Luke.

**Comment by mamrhein** [comment]
Hi Luke,
thanks for your PR. I appreciate your proposal to make this package usable for astronomers.
But I'm somewhat reluctant to integrate the new units into the already defined quantities. I think someone dealing with light-years doesn't care about millimeters and vice versa. The currently pre-defined quantities are meant for "earth-bound" measures. Adding units of astronomical scale would raise the range of magnitude between the largest and the smallest unit up to 10^30 or even more. That does far exceed the precision of the types used for the numerical part of quantities. ('f64' has less then 16 significant decimal digits!) 
Instead, I would prefer to define separate quantities with units of astronomical scale:
AstroTime:
ref-unit = Day
units = your proposed additions
AstroLength:
ref-unit: astronomical unit?
units: your proposed additions, plus kilometer as smallest unit? and Kiloparsec? / Megaparsec?
AstroMass:
ref-unit = Solar Mass?
units = your proposed additions
Is there also a unit at galactic scale?
For Speed I would add 'Speed of Light' as a unit to the existing quantity.
If you agree I would add three modules with the proposed quantities.
In any case, I would like you to review and double-check the definitions!
Best regards,
Michael

**Comment by mamrhein** [comment]
Hi Luke,
the proposal above jumps too short. Having additional quantities for the same base concept would render the derived quantities inconsistent. Dividing AstroLength by AstroTime wouldn't give Speed.
Providing quantities with units at a different scale needs to have a consistent set of base and derived quantities. I think this could best be done with a new crate, based on 'quantities', and providing an own definition of 'Length', 'Mass', 'Duration' etc., including all of the derived SI quantities. (A similar approach could be used for example with units at atomic and sub-atomic scale, usable for atomic and quantum physics.)
I will start a new package ('astronomical_quantities') and keep you posted. I still would like you to review the definitions and - if possible - provide some real-life test cases.
Best regards,
Michael

**Comment by mamrhein** [comment]
Hi Luke,
I created the crate 'astronomical-quantities' in a new branch named 'astro'.
May I ask you to have a look at the definitions and give me some feedback?
Thx in advance,
Michael

**Comment by mamrhein** [comment]
No feedback from OP.
Closing this.

**Comment by luke-magnusson** [comment]
Hey, thanks for taking the time to reviewing my pull request, and I totally understand your rational.

Sorry for not responding sooner. I'll take a look at astronomical_quantities ASAP.
